name = "Wild"
uuid = "42e5e773-7461-4e3f-a089-462a202deb8b"
authors = ["Koh Hashimoto"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
